version: "3.8"

services:
  django:
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    image: django:ross_blog
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - pgdb
    restart: always
  pgdb:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data/:rw


#  esearch:
#    image: elasticsearch:7.16.2
#    environment:
#      - discovery.type=single-node
#    ports:
#      - "9200:9200"